
import { Tabs } from 'expo-router';
import { View, Text, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons'; // Using Expo Vector Icons
import { COLORS, FONTS } from '../../src/constants/theme';

export default function TabLayout() {
  return (
      <Tabs
            screenOptions={{
                    headerShown: false, // Hide top header
                            tabBarShowLabel: false, // We will use custom icon+label
                                    tabBarStyle: {
                                              backgroundColor: '#FFFFFF',
                                                        borderTopWidth: 0,
                                                                  elevation: 5, // Shadow for Android
                                                                            shadowColor: '#000', // Shadow for iOS
                                                                                      shadowOffset: { width: 0, height: -2 },
                                                                                                shadowOpacity: 0.1,
                                                                                                          shadowRadius: 4,
                                                                                                                    height: Platform.OS === 'ios' ? 85 : 70,
                                                                                                                              paddingBottom: Platform.OS === 'ios' ? 30 : 10,
                                                                                                                                        paddingTop: 10,
                                                                                                                                                },
                                                                                                                                                        tabBarActiveTintColor: COLORS.primary,
                                                                                                                                                                tabBarInactiveTintColor: COLORS.gray,
                                                                                                                                                                      }}
                                                                                                                                                                          >
                                                                                                                                                                                {/* 🏠 Tab 1: Home (Search Bus) */}
                                                                                                                                                                                      <Tabs.Screen
                                                                                                                                                                                              name="index"
                                                                                                                                                                                                      options={{
                                                                                                                                                                                                                tabBarIcon: ({ focused }) => (
                                                                                                                                                                                                                            <View style={{ alignItems: 'center', justifyContent: 'center' }}>
                                                                                                                                                                                                                                          <Ionicons 
                                                                                                                                                                                                                                                          name={focused ? "home" : "home-outline"} 
                                                                                                                                                                                                                                                                          size={24} 
                                                                                                                                                                                                                                                                                          color={focused ? COLORS.primary : COLORS.gray} 
                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                      <Text style={{ 
                                                                                                                                                                                                                                                                                                                                      fontSize: 12, 
                                                                                                                                                                                                                                                                                                                                                      color: focused ? COLORS.primary : COLORS.gray,
                                                                                                                                                                                                                                                                                                                                                                      marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: focused ? 'bold' : 'normal'
                                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                                    Home
                                                                                                                                                                                                                                                                                                                                                                                                                                  </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 🚌 Tab 2: Bus Details (Driver Only) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Tabs.Screen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name="bus-details"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  options={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tabBarIcon: ({ focused }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <View style={{ alignItems: 'center', justifyContent: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Ionicons 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name={focused ? "bus" : "bus-outline"} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size={24} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color={focused ? COLORS.primary : COLORS.gray} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 12, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: focused ? COLORS.primary : COLORS.gray,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: focused ? 'bold' : 'normal'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Bus.driver
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Tabs>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
